package org.weishe.weichat.bean;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TODO.
 */
public class Todo implements Serializable {

	private Long id;
	private Integer todoId;
	private Integer whoId;
	private Boolean checked;
	private Integer type;
	private Integer fromId;
	private Integer groupId;
	private java.util.Date createDate;
	private Boolean complete;
	private Boolean agree;
	private String requestMsg;
	private String handleMsg;
	private String handleDate;
	private String todoSubject;

	public Todo() {
	}

	public Todo(Long id) {
		this.id = id;
	}

	public Todo(Long id, Integer todoId, Integer whoId, Boolean checked,
			Integer type, Integer fromId, Integer groupId,
			java.util.Date createDate, Boolean complete, Boolean agree,
			String requestMsg, String handleMsg, String handleDate,
			String todoSubject) {
		this.id = id;
		this.todoId = todoId;
		this.whoId = whoId;
		this.checked = checked;
		this.type = type;
		this.fromId = fromId;
		this.groupId = groupId;
		this.createDate = createDate;
		this.complete = complete;
		this.agree = agree;
		this.requestMsg = requestMsg;
		this.handleMsg = handleMsg;
		this.handleDate = handleDate;
		this.todoSubject = todoSubject;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Integer getTodoId() {
		return todoId;
	}

	public void setTodoId(Integer todoId) {
		this.todoId = todoId;
	}

	public Integer getWhoId() {
		return whoId;
	}

	public void setWhoId(Integer whoId) {
		this.whoId = whoId;
	}

	public Boolean getChecked() {
		return checked;
	}

	public void setChecked(Boolean checked) {
		this.checked = checked;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getFromId() {
		return fromId;
	}

	public void setFromId(Integer fromId) {
		this.fromId = fromId;
	}

	public Integer getGroupId() {
		return groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public java.util.Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(java.util.Date createDate) {
		this.createDate = createDate;
	}

	public Boolean getComplete() {
		return complete;
	}

	public void setComplete(Boolean complete) {
		this.complete = complete;
	}

	public Boolean getAgree() {
		return agree;
	}

	public void setAgree(Boolean agree) {
		this.agree = agree;
	}

	public String getRequestMsg() {
		return requestMsg;
	}

	public void setRequestMsg(String requestMsg) {
		this.requestMsg = requestMsg;
	}

	public String getHandleMsg() {
		return handleMsg;
	}

	public void setHandleMsg(String handleMsg) {
		this.handleMsg = handleMsg;
	}

	public String getHandleDate() {
		return handleDate;
	}

	public void setHandleDate(String handleDate) {
		this.handleDate = handleDate;
	}

	public String getTodoSubject() {
		return todoSubject;
	}

	public void setTodoSubject(String todoSubject) {
		this.todoSubject = todoSubject;
	}

}
